site_name: 'রোড টু হাইটেক ইন্ডাস্ট্রি: নেটওয়ার্ক/আইএসপি অটোমেশন'
theme:
  name: material
  language: bn

# Project information
site_url: https://aiwithr.github.io/automation/
site_author: রকিবুল হাসান
site_description: >-
  রোড টু হাইটেক ইন্ডাস্ট্রি:
  নেটওয়ার্ক/আইএসপি অটোমেশন

# Repository
repo_name: raqueeb/mltraining
repo_url: https://github.com/raqueeb/mltraining/
edit_uri: ""

# Copyright
copyright: সৃজনশীল লাইসেন্সিং ২০১৯ - ২০২৩ &copy; রকিবুল হাসান

# Configuration
theme:
  name: material
  # custom_dir: overrides
    features:
#    - navigation.tabs
#    - navigation.sections
    - navigation.expand
#    - navigation.instant
# - toc.integrate
  # 404 page
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: bn
  features:
  #  - tabs
    - instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: SiyamRupali
    code: SiyamRupali
  favicon: assets/favicon.png
  icon:
    logo: logo

extra_css:
  - stylesheets/extra.css
# Plugins
# plugins:
#    - pdf-export:
#        verbose: true
#        media_type: print
#        enabled_if_env: ENABLE_PDF_EXPORT
#        combined: true
#        combined_output_path: pdf/combined.pdf


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/raqueeb
    - icon: fontawesome/brands/facebook-messenger
      link: http://m.me/raqueeb
    - icon: fontawesome/brands/whatsapp
      link: tel:+8801713095767
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/raqueeb
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/raqueeb/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/raqueeb
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/raqueeb

# extra:
#   disqus: aiwithr

# Extensions

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: false
  - toc:
      permalink: false

markdown_extensions:
#  - toc:
#      permalink: ⚓︎
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: aiwithr
      repo: aibook
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
 
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.critic
  - pymdownx.smartsymbols
  - pymdownx.mark
#  - meta
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all

  - pymdownx.tasklist:
      custom_checkbox: true

hide:
#- navigation # Hide navigation
  - toc 
      
# বইয়ের গাছপালা
nav:
  - "নেটওয়ার্ক/আইএসপি অটোমেশন": index.md
  - অটোমেশন কেন লাগছে?: whyautomation.md
  - উৎসর্গ: frontmatter/dedication.md
  - কৃতজ্ঞতা এবং বাড়তি রিডিং: frontmatter/courtesy.md
  - কেন বইটা লিখতে চাইলাম?: why-writing.md
  - আমি কেন আইএসপিতে এলাম?: whyisp.md

  - প্রাথমিক 'বিল্ডিং ব্লক':
    - নেটওয়ার্কের ইন্টারফেস কী মানুষ?: interface.md
    - পাইথনের বেসিক ধারণা: python.md
    - পাইথন দিয়ে ডাটা এক্সেস: python_data.md
  - কৃত্রিম বুদ্ধিমত্তা এবং নেটওয়ার্ক ম্যানেজমেন্ট: software-is-eating-world.md
  - নেটওয়ার্ক কনফিগারেশন ম্যানেজমেন্ট অটোমেশন: network_config.md
  - পাইথন দিয়ে নেটওয়ার্কের কনফিগারেশন ব্যাকআপ: python_config_backup.md
 
#   - এআই, শুরুর ধারণা:

#     - কিভাবে এখানে এলাম?: start/how-did-we-arr.md
#     - কেন প্রয়োজন কৃত্রিম বুদ্ধিমত্তার?: start/why-ai.md
#     - ‘কৃত্রিম বুদ্ধিমত্তা’ জিনিসটা কি?: start/definition.md
#     - পেছনের ড্রাইভিং ফ্যাক্টরগুলো কী কী?: start/driving-factors.md
#     - কৃত্রিম বুদ্ধিমত্তার দুটো 'অ্যাপ্রোচ': start/two-approaches.md
#     - টেক্সটবুকের কিছু ডেফিনিশন: start/textbook-def.md
#     - অ্যালান টুরিং টেস্ট: start/turing-test.md
#     - যন্ত্রের উপলব্ধি বোধ, চাইনিজ-রুম যুক্তি: start/chinese-room.md
#     - মানুষ এবং যন্ত্র কিভাবে শেখে?: start/nlp-learning.md
#     - সিদ্ধান্তের 'লুপ' থেকে মানুষকে বের করে আনা: start/what-we-want.md
#     - ডাটা কিভাবে কথা বলে?: start/data-talks.md
#     - মেশিন লার্নিং কেন?: start/why-ml.md
#     - ডিপ লার্নিং ব্যাপারটা কী?: start/deep-learning.md
#     - শব্দের এমবেডিং প্রজেক্টর, ঘটনার সিগনেচার: start/embedding-connection.md
# #    - মানুষের এবং যন্ত্রের বায়াস, করনীয়: start/human-ai-bias.md

#   - আগাম ধারণার প্রশাসন:

#     - সরকার এবং কৃত্রিম বুদ্ধিমত্তা - শুরুর প্রস্তাবনা: frontmatter/government-ai.md
#     - ভবিষ্যতের সরকার এবং গ্লোবালাইজেশন ইফেক্ট: frontmatter/future-gov.md
#     - অপরাধ সনাক্তকরণ পদ্ধতি, ক্রাইম ডাটা: frontmatter/crime-prediction.md
#     - বাংলাদেশ এবং আগাম ধারণার প্রশাসন, কিভাবে?: frontmatter/govt-of-the-future.md
#     - কৃষক এবং অন্যান্য আত্মহত্যার যোগসূত্র: frontmatter/suicide-farmers.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto