site_name: 'রোড টু হাইটেক ইন্ডাস্ট্রি: নেটওয়ার্ক/আইএসপি অটোমেশন'
theme:
  name: material
  language: bn

# Project information
site_url: https://aiwithr.github.io/automation/
site_author: রকিবুল হাসান
site_description: >-
  রোড টু হাইটেক ইন্ডাস্ট্রি:
  নেটওয়ার্ক/আইএসপি অটোমেশন

# Repository
repo_name: raqueeb/mltraining
repo_url: https://github.com/raqueeb/mltraining/
edit_uri: ""

# Copyright
copyright: সৃজনশীল লাইসেন্সিং ২০১৯ - ২০২৩ &copy; রকিবুল হাসান

# Configuration
theme:
  name: material
#  custom_dir: material/overrides
  features:
#    - navigation.tabs
    - navigation.sections
#    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.footer
#    - navigation.instant
# - toc.integrate
  # 404 page
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: SiyamRupali
    code: SiyamRupali
  favicon: assets/favicon.png
  icon:
    logo: logo

extra_css:
  - stylesheets/extra.css
# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - exporter:
  #     formats:
  #       pdf:
  #         enabled: !ENV [MKDOCS_EXPORTER_PDF, true]
  #         concurrency: 8
  #         stylesheets:
  #           - stylesheets/pdf.scss
  #         covers:
  #           front: covers/front.html.j2
  #           back: covers/back.html.j2
  #         aggregator:
  #           enabled: true
  #           output: .well-known/site.pdf
  #           covers: all
  #     buttons:
  #       - title: Download as PDF
  #         icon: material-file-download-outline
  #         enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
  #         attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
#  - minify:
#      minify_html: true

# Hooks
# hooks:
#  - material/overrides/hooks/shortcodes.py
#  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
# Customization
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/raqueeb
    - icon: fontawesome/brands/facebook-messenger
      link: http://m.me/raqueeb
    - icon: fontawesome/brands/whatsapp
      link: tel:+8801713095767
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/raqueeb
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/raqueeb/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/raqueeb
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/raqueeb

# extra:
#   disqus: aiwithr

# Extensions

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
   
# বইয়ের গাছপালা
nav:
  - কেন নেটওয়ার্ক অটোমেশন?: index.md
  - পেছনের দর্শন:
    - অটোমেশন নিয়ে গল্প: whyautomation.md
#    - প্রজেক্ট অটোমেশন: p_automation.md
    - বইটাকে কিভাবে সাজানো হয়েছে?: organization.md
    - উৎসর্গ: dedication.md
    - কৃতজ্ঞতা এবং বাড়তি রিডিং: courtesy.md
#    - কেন বইটা লিখতে চাইলাম?: why-writing.md
  - প্রাথমিক 'বিল্ডিং ব্লক':
    - নেটওয়ার্কের ইন্টারফেস মানুষ কেন হবে?: interface.md
    - নেটওয়ার্ক ইন্ডাস্ট্রির জন্য কিছু ইমারজিং ট্রেন্ড: emerging_trend.md
#    - তৈরি করি এনভায়রনমেন্ট: environment.md
    - তৈরি করি এনভায়রনমেন্ট: environment1.md
#    - ভার্চুয়ালাইজড এনভায়রনমেন্ট: virtual.md
  - পাইথন নিয়ে গল্প:
#    - পাইথনের বেসিক ধারণা: python.md
    - পাইথনের বেসিক ধারণা: python1.md
    - তিনটা পাইথনের উদাহরন: three_ex.md
    - পাইথন দিয়ে ডাটা এক্সেস: python_data.md
  - এপিআই এর খেলা:
    - এপিআই দিয়ে কোড: api_code.md
#    - হঠাৎ করে এপিআই?: why_api.md
    - পোস্টম্যানের খেলা: postman.md
    - রেস্ট এপিআই নিয়ে কাজ: rest_api.md
#    - পাইথনের ওয়েবসার্ভিসেস: python_webserv.md
  - নেটওয়ার্ক ইঞ্জিনিয়ারদের জন্য ডাটা ফরম্যাট:
      - ওয়াইএএমএল (YAML): yaml.md
      - এক্সএমএল (XML): xml.md
      - জেসন (JSON): json.md
#      - পাইথনের টেমপ্লেটিং ইঞ্জিন: jinja2.md
      - পাইথনের টেমপ্লেটিং ইঞ্জিন: jinja2-1.md
  - নেটফ্লিক্স স্টাইল পাইলট:
    - নেটওয়ার্ক কনফিগারেশন ম্যানেজমেন্ট অটোমেশন: network_config.md
    - পাইথন দিয়ে নেটওয়ার্কের কনফিগারেশন ব্যাকআপ: python_config_backup.md        
  - ডাটা মডেল আর্কিটেকচার:
    - ইয়াং ডাটা মডেলিং ল্যাঙ্গুয়েজ: yang.md
    - রেস্ট এপিআই কনফিগারেশন (restconf): restconf.md
    - নেটওয়ার্ক কনফিগারেশন (netconf): netconf.md
    - ইয়াং স্যুটের ব্যবহার: yangsuite.md
    - ইয়াং মডেলে রেস্টকন্ফ: restconf_yang.md
  - আমাদের কিছু 'ইউজড' কেস:
#    - কৃত্রিম বুদ্ধিমত্তা এবং নেটওয়ার্ক ম্যানেজমেন্ট: software-is-eating-world.md
    - নেটমিকো/ওয়াইএমএল দিয়ে কনফিগারেশন পুশ: netmiko_yml_push.md
    - মাইক্রোটিকের এপিআই দিয়ে খেলা: mikrotik_api.md
    - নেটওয়ার্ক অটোমেশনে অ্যান্সিবল: ansible.md
    - অ্যান্সিবল দিয়ে সুইচ+রাউটারে+মাইক্রোটিকে কাজ: ansible_2_tasks.md 
    - পাইএটিএস+জেনি এসএলএ/বিজিপি মনিটরিং: pyats_genie.md
    - সল্টস্ট্যাক দিয়ে ফায়ারওয়াল ম্যানেজমেন্ট: SaltStack.md
  - আধুনিক আইএসপি ম্যানেজমেন্ট:
    - ইন্টেলিজেন্ট ওয়াই-ফাই ম্যানেজমেন্ট: wifi.md 
  - দ্বিতীয় পর্ব কি আসবে?:
    - সামনে কোথায় যাবো?: final.md
  - পরিশিষ্ট:
    - আমি কেন আইএসপিতে এলাম?: whyisp.md

 